"""hito atlas

Revision ID: 455f4df74280
Revises: 648de3eb0f2b
Create Date: 2026-06-01 02:46:19.708668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '455f4df74280'
down_revision: Union[str, Sequence[str], None] = '648de3eb0f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hito_atlas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('internacion_id', sa.UUID(), nullable=True),
    sa.Column('cama_gestion_id', sa.UUID(), nullable=True),
    sa.Column('hito_codigo', sa.String(length=100), nullable=False),
    sa.Column('actor_rol', sa.String(length=40), nullable=True),
    sa.Column('actor_nombre', sa.String(length=100), nullable=True),
    sa.Column('metadata_evento', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('registrado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sincronizado_core', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cama_gestion_id'], ['cama_gestion.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internacion_id'], ['internacion_local.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hito_atlas_cama_gestion_id'), 'hito_atlas', ['cama_gestion_id'], unique=False)
    op.create_index(op.f('ix_hito_atlas_hito_codigo'), 'hito_atlas', ['hito_codigo'], unique=False)
    op.create_index(op.f('ix_hito_atlas_internacion_id'), 'hito_atlas', ['internacion_id'], unique=False)
    op.create_index(op.f('ix_hito_atlas_registrado_at'), 'hito_atlas', ['registrado_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hito_atlas_registrado_at'), table_name='hito_atlas')
    op.drop_index(op.f('ix_hito_atlas_internacion_id'), table_name='hito_atlas')
    op.drop_index(op.f('ix_hito_atlas_hito_codigo'), table_name='hito_atlas')
    op.drop_index(op.f('ix_hito_atlas_cama_gestion_id'), table_name='hito_atlas')
    op.drop_table('hito_atlas')
    # ### end Alembic commands ###
