"""reserva

Revision ID: 4dd9e83bb465
Revises: 455f4df74280
Create Date: 2026-06-02 00:00:22.571573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4dd9e83bb465'
down_revision: Union[str, Sequence[str], None] = '455f4df74280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserva',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cama_gestion_id', sa.UUID(), nullable=False),
    sa.Column('internacion_id', sa.UUID(), nullable=False),
    sa.Column('motivo', sa.Enum('QUIRURGICA', 'PASE_INTERNO', 'INGRESO_PROGRAMADO', name='motivo_reserva'), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'CUMPLIDA', 'CANCELADA', 'VENCIDA', name='estado_reserva'), nullable=False),
    # tipo_cama YA existe (lo creó la migración de cama_gestion): se REUSA con
    # create_type=False para NO intentar recrearlo.
    sa.Column('tipo_cama_requerido', postgresql.ENUM('CAMA_INTERNACION', 'UTI', 'UCO', name='tipo_cama', create_type=False), nullable=False),
    sa.Column('motivo_cancelacion', sa.String(length=200), nullable=True),
    sa.Column('creada_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resuelta_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cama_gestion_id'], ['cama_gestion.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internacion_id'], ['internacion_local.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reserva_cama_gestion_id'), 'reserva', ['cama_gestion_id'], unique=False)
    op.create_index(op.f('ix_reserva_creada_at'), 'reserva', ['creada_at'], unique=False)
    op.create_index(op.f('ix_reserva_estado'), 'reserva', ['estado'], unique=False)
    op.create_index(op.f('ix_reserva_internacion_id'), 'reserva', ['internacion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reserva_internacion_id'), table_name='reserva')
    op.drop_index(op.f('ix_reserva_estado'), table_name='reserva')
    op.drop_index(op.f('ix_reserva_creada_at'), table_name='reserva')
    op.drop_index(op.f('ix_reserva_cama_gestion_id'), table_name='reserva')
    op.drop_table('reserva')
    # ### end Alembic commands ###
    # FIX: dropear SOLO los enums NUEVOS de esta migración (checkfirst=True para tolerar
    # downgrades parciales). tipo_cama NO se dropea: lo sigue usando cama_gestion.
    sa.Enum(name='estado_reserva').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='motivo_reserva').drop(op.get_bind(), checkfirst=True)
