"""paciente local e internacion local

Revision ID: 5d5afe1bf2a5
Revises: 
Create Date: 2026-05-31 16:35:13.619055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5afe1bf2a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente_local',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('core_patient_id', sa.UUID(), nullable=True),
    sa.Column('nhc_externo', sa.String(length=50), nullable=True),
    sa.Column('creado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paciente_local_dni'), 'paciente_local', ['dni'], unique=False)
    op.create_table('internacion_local',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_local_id', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.Enum('QUIRURGICA_PROGRAMADA', 'QUIRURGICA_URGENCIA', 'CLINICA', 'GUARDIA_OBSERVACION', 'CRITICA', 'OBSTETRICA', name='categoria_internacion'), nullable=False),
    sa.Column('comodidad_requerida', sa.Enum('SIN_PREFERENCIA', 'COMPARTIDA', 'INDIVIDUAL', 'SUITE', name='tipo_comodidad'), nullable=True),
    sa.Column('servicio_codigo', sa.String(length=10), nullable=True),
    sa.Column('core_episodio_id', sa.UUID(), nullable=True),
    sa.Column('iniciada_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalizada_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paciente_local_id'], ['paciente_local.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internacion_local_categoria'), 'internacion_local', ['categoria'], unique=False)
    op.create_index(op.f('ix_internacion_local_iniciada_at'), 'internacion_local', ['iniciada_at'], unique=False)
    op.create_index(op.f('ix_internacion_local_paciente_local_id'), 'internacion_local', ['paciente_local_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internacion_local_paciente_local_id'), table_name='internacion_local')
    op.drop_index(op.f('ix_internacion_local_iniciada_at'), table_name='internacion_local')
    op.drop_index(op.f('ix_internacion_local_categoria'), table_name='internacion_local')
    op.drop_table('internacion_local')
    op.drop_index(op.f('ix_paciente_local_dni'), table_name='paciente_local')
    op.drop_table('paciente_local')
    # ### end Alembic commands ###
    # FIX: drop de los tipos enum (autogenerate los crea pero no los dropea).
    # checkfirst=True para tolerar downgrades parciales (no falla si ya no existe).
    sa.Enum(name='tipo_comodidad').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='categoria_internacion').drop(op.get_bind(), checkfirst=True)
