"""cobertura en internacion

Revision ID: 60d4d29949ac
Revises: 80a3253b85a9
Create Date: 2026-06-03 16:44:59.324991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d4d29949ac'
down_revision: Union[str, Sequence[str], None] = '80a3253b85a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internacion_local', sa.Column('cobertura', sa.String(length=100), nullable=True))
    op.add_column('internacion_local', sa.Column('plan_cobertura', sa.String(length=60), nullable=True))
    op.add_column('internacion_local', sa.Column('numero_socio', sa.String(length=60), nullable=True))
    op.add_column('internacion_local', sa.Column('nota_cobertura', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('internacion_local', 'nota_cobertura')
    op.drop_column('internacion_local', 'numero_socio')
    op.drop_column('internacion_local', 'plan_cobertura')
    op.drop_column('internacion_local', 'cobertura')
    # ### end Alembic commands ###
