"""cama gestion

Revision ID: 648de3eb0f2b
Revises: 5d5afe1bf2a5
Create Date: 2026-05-31 16:41:57.438717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '648de3eb0f2b'
down_revision: Union[str, Sequence[str], None] = '5d5afe1bf2a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cama_gestion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('CAMA_INTERNACION', 'UTI', 'UCO', name='tipo_cama'), nullable=False),
    sa.Column('comodidad', sa.Enum('SIN_PREFERENCIA', 'COMPARTIDA', 'INDIVIDUAL', 'SUITE', name='tipo_comodidad'), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=False),
    sa.Column('estado_gestion', sa.Enum('DISPONIBLE', 'RESERVADA', 'OCUPADA', 'PROCESO_DE_ALTA', 'LIMPIEZA_TERMINAL', 'BLOQUEADA', name='estado_cama_gestion'), nullable=False),
    sa.Column('internacion_actual_id', sa.UUID(), nullable=True),
    sa.Column('motivo_bloqueo', sa.String(length=200), nullable=True),
    sa.Column('core_location_id', sa.UUID(), nullable=True),
    sa.Column('actualizado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['internacion_actual_id'], ['internacion_local.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cama_gestion_estado_gestion'), 'cama_gestion', ['estado_gestion'], unique=False)
    op.create_index(op.f('ix_cama_gestion_tipo'), 'cama_gestion', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cama_gestion_tipo'), table_name='cama_gestion')
    op.drop_index(op.f('ix_cama_gestion_estado_gestion'), table_name='cama_gestion')
    op.drop_table('cama_gestion')
    # ### end Alembic commands ###
