"""pase servicio

Revision ID: 80a3253b85a9
Revises: 4dd9e83bb465
Create Date: 2026-06-02 18:00:12.902206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '80a3253b85a9'
down_revision: Union[str, Sequence[str], None] = '4dd9e83bb465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pase_servicio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('internacion_id', sa.UUID(), nullable=False),
    sa.Column('cama_origen_id', sa.UUID(), nullable=False),
    sa.Column('cama_destino_id', sa.UUID(), nullable=True),
    sa.Column('reserva_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.Enum('SOLICITADO', 'CAMA_ASIGNADA', 'EN_TRASLADO', 'CONFIRMADO', 'CANCELADO', name='estado_pase'), nullable=False),
    # tipo_cama YA existe (lo creó la migración de cama_gestion): se REUSA con
    # create_type=False para NO intentar recrearlo.
    sa.Column('tipo_cama_destino', postgresql.ENUM('CAMA_INTERNACION', 'UTI', 'UCO', name='tipo_cama', create_type=False), nullable=False),
    sa.Column('motivo_cancelacion', sa.String(length=200), nullable=True),
    sa.Column('solicitado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelado_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cama_destino_id'], ['cama_gestion.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cama_origen_id'], ['cama_gestion.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internacion_id'], ['internacion_local.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reserva.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pase_servicio_cama_origen_id'), 'pase_servicio', ['cama_origen_id'], unique=False)
    op.create_index(op.f('ix_pase_servicio_estado'), 'pase_servicio', ['estado'], unique=False)
    op.create_index(op.f('ix_pase_servicio_internacion_id'), 'pase_servicio', ['internacion_id'], unique=False)
    op.create_index(op.f('ix_pase_servicio_solicitado_at'), 'pase_servicio', ['solicitado_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pase_servicio_solicitado_at'), table_name='pase_servicio')
    op.drop_index(op.f('ix_pase_servicio_internacion_id'), table_name='pase_servicio')
    op.drop_index(op.f('ix_pase_servicio_estado'), table_name='pase_servicio')
    op.drop_index(op.f('ix_pase_servicio_cama_origen_id'), table_name='pase_servicio')
    op.drop_table('pase_servicio')
    # ### end Alembic commands ###
    # FIX: dropear SOLO el enum NUEVO de esta migración (checkfirst=True para tolerar
    # downgrades parciales). tipo_cama NO se dropea: lo usan cama_gestion y reserva.
    sa.Enum(name='estado_pase').drop(op.get_bind(), checkfirst=True)
