"""checklist de alta

Revision ID: a97dacdbf944
Revises: d60ecce6ce81
Create Date: 2026-06-03 00:31:54.535728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a97dacdbf944'
down_revision: Union[str, Sequence[str], None] = 'd60ecce6ce81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paso_alta_catalogo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    # categoria_internacion YA existe (la creó la migración de internacion_local): se
    # REUSA con create_type=False para NO intentar recrearla.
    sa.Column('categoria_aplica', postgresql.ENUM('QUIRURGICA_PROGRAMADA', 'QUIRURGICA_URGENCIA', 'CLINICA', 'GUARDIA_OBSERVACION', 'CRITICA', 'OBSTETRICA', name='categoria_internacion', create_type=False), nullable=True),
    sa.Column('bloqueante', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paso_alta_catalogo_codigo'), 'paso_alta_catalogo', ['codigo'], unique=True)
    op.create_table('paso_alta_internacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('internacion_id', sa.UUID(), nullable=False),
    sa.Column('paso_catalogo_id', sa.UUID(), nullable=False),
    sa.Column('era_bloqueante', sa.Boolean(), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.Column('completado_por_rol', sa.String(length=40), nullable=True),
    sa.Column('completado_por_nombre', sa.String(length=100), nullable=True),
    sa.Column('completado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creada_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['internacion_id'], ['internacion_local.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paso_catalogo_id'], ['paso_alta_catalogo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paso_alta_internacion_internacion_id'), 'paso_alta_internacion', ['internacion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paso_alta_internacion_internacion_id'), table_name='paso_alta_internacion')
    op.drop_table('paso_alta_internacion')
    op.drop_index(op.f('ix_paso_alta_catalogo_codigo'), table_name='paso_alta_catalogo')
    op.drop_table('paso_alta_catalogo')
    # ### end Alembic commands ###
    # No se dropea ningún enum: esta migración NO crea tipos nuevos (categoria_internacion
    # se reusa con create_type=False y la sigue usando internacion_local).
