"""nota cama

Revision ID: d60ecce6ce81
Revises: 4dd9e83bb465
Create Date: 2026-06-03 00:16:06.276667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd60ecce6ce81'
down_revision: Union[str, Sequence[str], None] = '4dd9e83bb465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nota_cama',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cama_gestion_id', sa.UUID(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('creada_por_rol', sa.String(length=40), nullable=True),
    sa.Column('creada_por_nombre', sa.String(length=100), nullable=True),
    sa.Column('creada_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modificada_por_rol', sa.String(length=40), nullable=True),
    sa.Column('modificada_por_nombre', sa.String(length=100), nullable=True),
    sa.Column('modificada_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cama_gestion_id'], ['cama_gestion.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nota_cama_cama_gestion_id'), 'nota_cama', ['cama_gestion_id'], unique=False)
    op.create_index(op.f('ix_nota_cama_creada_at'), 'nota_cama', ['creada_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nota_cama_creada_at'), table_name='nota_cama')
    op.drop_index(op.f('ix_nota_cama_cama_gestion_id'), table_name='nota_cama')
    op.drop_table('nota_cama')
    # ### end Alembic commands ###
