"""egreso y satelites

Revision ID: e8546bf296d3
Revises: 60d4d29949ac
Create Date: 2026-06-10 12:19:50.534348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8546bf296d3'
down_revision: Union[str, Sequence[str], None] = '60d4d29949ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egresos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('internacion_local_id', sa.UUID(), nullable=False),
    sa.Column('cama_gestion_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('medio_egreso', sa.String(length=30), nullable=False),
    sa.Column('mantenimiento_requerido', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('trabado_desde', sa.DateTime(timezone=True), nullable=True),
    sa.Column('egreso_admin_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('salida_fisica_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cama_gestion_id'], ['cama_gestion.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internacion_local_id'], ['internacion_local.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_egresos_cama_gestion_id'), 'egresos', ['cama_gestion_id'], unique=False)
    op.create_index(op.f('ix_egresos_created_at'), 'egresos', ['created_at'], unique=False)
    op.create_index(op.f('ix_egresos_estado'), 'egresos', ['estado'], unique=False)
    op.create_index(op.f('ix_egresos_internacion_local_id'), 'egresos', ['internacion_local_id'], unique=False)
    op.create_index('uq_egreso_activo_por_cama', 'egresos', ['cama_gestion_id'], unique=True, postgresql_where=sa.text("estado IN ('info', 'bloqueado', 'egreso_admin')"))
    op.create_table('discrepancias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('egreso_id', sa.UUID(), nullable=False),
    sa.Column('motivo', sa.String(length=60), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['egreso_id'], ['egresos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discrepancias_egreso_id'), 'discrepancias', ['egreso_id'], unique=False)
    op.create_table('item_checklist_egreso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('egreso_id', sa.UUID(), nullable=False),
    sa.Column('responsable', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('requerido_legal', sa.Boolean(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('hora_marcado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('autor', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['egreso_id'], ['egresos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_checklist_egreso_egreso_id'), 'item_checklist_egreso', ['egreso_id'], unique=False)
    op.create_table('item_checklist_limpieza',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('egreso_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('hora_marcado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('autor', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['egreso_id'], ['egresos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_checklist_limpieza_egreso_id'), 'item_checklist_limpieza', ['egreso_id'], unique=False)
    op.create_table('nota_egreso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('egreso_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['egreso_id'], ['egresos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nota_egreso_egreso_id'), 'nota_egreso', ['egreso_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nota_egreso_egreso_id'), table_name='nota_egreso')
    op.drop_table('nota_egreso')
    op.drop_index(op.f('ix_item_checklist_limpieza_egreso_id'), table_name='item_checklist_limpieza')
    op.drop_table('item_checklist_limpieza')
    op.drop_index(op.f('ix_item_checklist_egreso_egreso_id'), table_name='item_checklist_egreso')
    op.drop_table('item_checklist_egreso')
    op.drop_index(op.f('ix_discrepancias_egreso_id'), table_name='discrepancias')
    op.drop_table('discrepancias')
    op.drop_index('uq_egreso_activo_por_cama', table_name='egresos', postgresql_where=sa.text("estado IN ('info', 'bloqueado', 'egreso_admin')"))
    op.drop_index(op.f('ix_egresos_internacion_local_id'), table_name='egresos')
    op.drop_index(op.f('ix_egresos_estado'), table_name='egresos')
    op.drop_index(op.f('ix_egresos_created_at'), table_name='egresos')
    op.drop_index(op.f('ix_egresos_cama_gestion_id'), table_name='egresos')
    op.drop_table('egresos')
    # ### end Alembic commands ###
